baseURL = "https://anphiax.github.io/mynotes/"
languageCode = "en-us"
title = "My Notes"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  math = true
  katex = true
